apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zabbix-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zabbix-role
subjects:
  - kind: ServiceAccount
    name: zabbix
roleRef:
  kind: Role
  name: zabbix-role
  apiGroup: rbac.authorization.k8s.io
