apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: zabbix
spec:
  groups:
  - system:authenticated
  request: <base_64_encoded_csr>
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
